language: dart

dart:
  - dev

before_script:
  - pub get

script:
  - dartanalyzer lib web --fatal-warnings
  - dartfmt --dry-run --line-length 120 --set-exit-if-changed .

cache:
  directories:
    - $HOME/.pub-cache
