name: fckng_portfolio
version: 0.0.1
description: Fckng portfolio.
author: Honza Bittner
homepage: http://honzabittner.cz

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  intl: '^0.15.7'
  meta: '^1.1.7'

dev_dependencies:
  build_runner: '^1.2.5'
  build_web_compilers: '^1.1.0'
