name: fckng_portfolio
version: 0.0.1
description: Fckng portfolio.
author: Honza Bittner
homepage: http://honzabittner.cz

environment:
  sdk: '>=2.0.0-dev.46.0 <2.0.0'

dependencies:
  intl: '^0.15.2'
  meta: '^1.1.2'

dev_dependencies:
  build_runner: '^0.8.7'
  build_web_compilers: '^0.3.7+3'
