name: portfolio
description: An absolute bare-bones web app.
version: 2021.1.0
homepage: https://tenhobi.dev
publish_to: none

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  lints: ^1.0.0
