name: fckng_portfolio
version: 0.0.1
description: Fckng portfolio.
author: Honza Bittner
homepage: http://honzabittner.cz

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  intl: ^0.16.1
  meta: ^1.2.4

dev_dependencies:
  build_runner: ^1.10.13
  build_web_compilers: ^2.12.0
